// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQc02vTXIsDh00bRyt7CyqnTiq_7Z-fGU',
    appId: '1:191268747522:web:d5b9f29a7c42af9b736a1b',
    messagingSenderId: '191268747522',
    projectId: 'rol-embarque',
    authDomain: 'rol-embarque.firebaseapp.com',
    storageBucket: 'rol-embarque.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKP5_yfzvF_Rx6a0xdne9E6OFlva1z2eU',
    appId: '1:191268747522:android:1192d808fc518bc8736a1b',
    messagingSenderId: '191268747522',
    projectId: 'rol-embarque',
    storageBucket: 'rol-embarque.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbxWy36YEht3MWEb_MA4epjJZHrsBwOT0',
    appId: '1:191268747522:ios:8b19243f0566590a736a1b',
    messagingSenderId: '191268747522',
    projectId: 'rol-embarque',
    storageBucket: 'rol-embarque.firebasestorage.app',
    iosBundleId: 'com.example.rolEmbarque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbxWy36YEht3MWEb_MA4epjJZHrsBwOT0',
    appId: '1:191268747522:ios:8b19243f0566590a736a1b',
    messagingSenderId: '191268747522',
    projectId: 'rol-embarque',
    storageBucket: 'rol-embarque.firebasestorage.app',
    iosBundleId: 'com.example.rolEmbarque',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQc02vTXIsDh00bRyt7CyqnTiq_7Z-fGU',
    appId: '1:191268747522:web:bd1ab729fc224b40736a1b',
    messagingSenderId: '191268747522',
    projectId: 'rol-embarque',
    authDomain: 'rol-embarque.firebaseapp.com',
    storageBucket: 'rol-embarque.firebasestorage.app',
  );
}
